[application]

[web.app]

# HTML title tag content
title = "pino"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]

identifier = "com.acrilique.pino"
publisher = "acrilique"
copyright = "Copyright 2026 Lluc Simó Margalef"
category = "Utility"
icon = [
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.ico"
]

[bundle.macos]
signing_identity = "Developer ID Application: Lluc Simó Margalef (BJPC4PHT7X)"
hardened_runtime = true
