name: Build and Test
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
permissions: {}

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      package-types: appimage
                      no-strip: true
                    - os: windows-latest
                      package-types: msi
                      no-strip: false
        runs-on: ${{ matrix.os }}
        permissions:
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Install Linux dependencies
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential libwebkit2gtk-4.1-dev libayatana-appindicator3-dev curl wget file libxdo-dev libssl-dev librsvg2-dev lld

            - name: Print Rust version
              run: rustc -vV

            - name: Install Dioxus CLI
              run: cargo install dioxus-cli --locked

            - name: Bundle app
              run: dx bundle --release --desktop --package-types "${{ matrix.package-types }}"
              env:
                  NO_STRIP: ${{ matrix.no-strip }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: pino-${{ runner.os }}
                  path: target/dx/pino/bundle/